[tool.poetry]
name = "noteblock-generator"
version = "0.2.1"
description = "Generate music compositions in Minecraft noteblocks"
authors = ["Felix Fourcolor <felix.fourcolor@gmail.com>"]
readme = "README.md"
license = "CC0-1.0"
packages = [{include = "noteblock_generator"}]
homepage = "https://www.youtube.com/@felixfourcolor"
repository = "https://github.com/FelixFourcolor/noteblock-generator"
keywords = ["minecraft", "noteblock"]

[tool.poetry.scripts]
noteblock-generator = "noteblock_generator.__main__:main"

[tool.poetry.group.dev]
optional = true

[tool.poetry.dependencies]
python = ">=3.10, <3.13"
amulet-core = "^1.9.21"
PyMCTranslate = "^1.2.22"
colorama = ">=0.4.6"
pydantic = "^2.1"

[tool.poetry.group.dev.dependencies]
pyright = "==1.1.345"
ruff = ">=0.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
pythonVersion = "3.10"
reportIncompatibleMethodOverride = false
strictParameterNoneValue = false

[tool.ruff]
target-version = "py310"
show-fixes = true
cache-dir = "~/.cache/ruff"
line-length = 120
lint.select = ["A", "C4", "E", "F", "I", "PTH", "RUF", "SIM", "SLF", "UP", "W"]
lint.ignore = ["RUF013", "TCH", "UP007", "UP035"]
