allowBuilds:
  esbuild: true
  inotify: true
minimumReleaseAgeExclude:
  - '@typia/interface@14.0.5'
  - '@typia/utils@14.0.5'
  - '@vitest/coverage-v8@5.0.0'
  - '@vitest/mocker@5.0.0'
  - '@vitest/spy@5.0.0'
  - typia@14.0.5
  - vitest@5.0.0
  - '@vitest/pretty-format@5.0.0'
  - '@vitest/ui@5.0.0'
  - '@vitest/utils@5.0.0'
  - '@biomejs/biome@2.5.12'
  - '@biomejs/cli-darwin-arm64@2.5.12'
  - '@biomejs/cli-darwin-x64@2.5.12'
  - '@biomejs/cli-linux-arm64-musl@2.5.12'
  - '@biomejs/cli-linux-arm64@2.5.12'
  - '@biomejs/cli-linux-x64-musl@2.5.12'
  - '@biomejs/cli-linux-x64@2.5.12'
  - '@biomejs/cli-win32-arm64@2.5.12'
  - '@biomejs/cli-win32-x64@2.5.12'
